/// Karnaugh map minimization engine.
///
/// Pure Dart (no Flutter imports) so it can be unit-tested in isolation.
///
/// Uses the Quine–McCluskey method: prime implicants are generated by
/// iteratively combining patterns, essential implicants are selected first
/// and the remaining cover is solved exactly with branch & bound, minimizing
/// (1) number of terms and (2) number of literals. Ties between equally
/// minimal covers are broken by visual quality on the map (fewer wrapping
/// groups, larger areas), so the drawn grouping matches what a textbook
/// would choose.
///
/// Bit convention: `variables[0]` is the most significant bit of a minterm
/// index, matching how [TruthTable] builds its row combinations.
library;

enum KarnaughForm { sop, pos }

/// Supported variable counts for the visual map (2x2, 2x4 and 4x4 layouts).
const int kMinKarnaughVariables = 2;
const int kMaxKarnaughVariables = 4;

class KarnaughCellRef {
  final int row;
  final int col;

  const KarnaughCellRef(this.row, this.col);

  @override
  bool operator ==(Object other) =>
      other is KarnaughCellRef && other.row == row && other.col == col;

  @override
  int get hashCode => Object.hash(row, col);
}

/// One implicant of the minimal cover, ready to be drawn and listed.
class KarnaughGroup {
  /// Quine–McCluskey pattern over [KarnaughResult.variables], MSB first.
  /// `1` / `0` mean the variable is fixed, `-` means it was eliminated.
  final String pattern;

  /// Term using the app's notation (e.g. `(¬A ∧ C)` for SOP), so the result
  /// can be typed back into the calculator.
  final String term;

  /// Cells of the map covered by this implicant.
  final List<KarnaughCellRef> cells;

  const KarnaughGroup({
    required this.pattern,
    required this.term,
    required this.cells,
  });
}

class KarnaughResult {
  final KarnaughForm form;
  final List<String> variables;

  final int rowCount;
  final int colCount;

  /// Variables assigned to rows/columns (e.g. `AB` and `CD` for 4 variables).
  final String rowVariables;
  final String colVariables;

  /// Gray-code bit labels for each row/column (e.g. `00, 01, 11, 10`).
  final List<String> rowLabels;
  final List<String> colLabels;

  /// `values[row][col]` is the function output (0 or 1) for that cell.
  final List<List<int>> values;

  /// `minterms[row][col]` is the minterm index of that cell.
  final List<List<int>> minterms;

  /// Minimal cover. Empty when the function is constant.
  final List<KarnaughGroup> groups;

  /// Minimized expression in app notation (`¬`, `∧`, `∨`), or `1` / `0`
  /// when the function is constant.
  final String expression;

  final bool isConstant;

  const KarnaughResult({
    required this.form,
    required this.variables,
    required this.rowCount,
    required this.colCount,
    required this.rowVariables,
    required this.colVariables,
    required this.rowLabels,
    required this.colLabels,
    required this.values,
    required this.minterms,
    required this.groups,
    required this.expression,
    required this.isConstant,
  });
}

class KarnaughSolver {
  KarnaughSolver._();

  /// Minimize the function defined by [minterms] (indices where f = 1)
  /// over [variables]. SOP groups the 1s, POS groups the 0s.
  static KarnaughResult solve({
    required List<String> variables,
    required Set<int> minterms,
    required KarnaughForm form,
  }) {
    final n = variables.length;
    if (n < kMinKarnaughVariables || n > kMaxKarnaughVariables) {
      throw ArgumentError(
        'Karnaugh maps support $kMinKarnaughVariables-$kMaxKarnaughVariables '
        'variables, got $n',
      );
    }

    final colBits = (n + 1) ~/ 2;
    final rowBits = n - colBits;
    final rowLabels = _grayCodes(rowBits);
    final colLabels = _grayCodes(colBits);
    final rowCount = rowLabels.length;
    final colCount = colLabels.length;

    final values = List.generate(rowCount, (_) => List.filled(colCount, 0));
    final cellMinterms = List.generate(
      rowCount,
      (_) => List.filled(colCount, 0),
    );
    // Cell position of every minterm index, to map implicants back to cells.
    final positionOf = List<KarnaughCellRef>.filled(
      1 << n,
      const KarnaughCellRef(0, 0),
    );

    for (int r = 0; r < rowCount; r++) {
      for (int c = 0; c < colCount; c++) {
        final index =
            (int.parse(rowLabels[r], radix: 2) << colBits) |
            int.parse(colLabels[c], radix: 2);
        cellMinterms[r][c] = index;
        values[r][c] = minterms.contains(index) ? 1 : 0;
        positionOf[index] = KarnaughCellRef(r, c);
      }
    }

    final rowVariables = variables.sublist(0, rowBits).join();
    final colVariables = variables.sublist(rowBits).join();

    KarnaughResult buildResult({
      required List<KarnaughGroup> groups,
      required String expression,
      required bool isConstant,
    }) {
      return KarnaughResult(
        form: form,
        variables: variables,
        rowCount: rowCount,
        colCount: colCount,
        rowVariables: rowVariables,
        colVariables: colVariables,
        rowLabels: rowLabels,
        colLabels: colLabels,
        values: values,
        minterms: cellMinterms,
        groups: groups,
        expression: expression,
        isConstant: isConstant,
      );
    }

    final targetValue = form == KarnaughForm.sop ? 1 : 0;
    final targets = <int>[
      for (int m = 0; m < (1 << n); m++)
        if ((minterms.contains(m) ? 1 : 0) == targetValue) m,
    ];

    if (targets.isEmpty) {
      return buildResult(
        groups: const [],
        expression: form == KarnaughForm.sop ? '0' : '1',
        isConstant: true,
      );
    }
    if (targets.length == (1 << n)) {
      return buildResult(
        groups: const [],
        expression: form == KarnaughForm.sop ? '1' : '0',
        isConstant: true,
      );
    }

    final candidates = _solveExactPatterns(n, targets);
    final best = _pickBestCandidate(
      candidates,
      n,
      targets,
      positionOf,
      rowCount,
      colCount,
    );

    final groups = <KarnaughGroup>[];
    for (final pattern in best) {
      final covered =
          targets.where((m) => _matches(pattern, _toBinary(m, n))).toList()
            ..sort();
      groups.add(
        KarnaughGroup(
          pattern: pattern,
          term: _patternToTerm(pattern, variables, form),
          cells: [for (final m in covered) positionOf[m]],
        ),
      );
    }

    final expression = groups
        .map((g) => g.term)
        .join(form == KarnaughForm.sop ? ' ∨ ' : ' ∧ ');

    return buildResult(groups: groups, expression: expression, isConstant: false);
  }

  // ── Quine–McCluskey ────────────────────────────────────────────────────

  static String _toBinary(int value, int width) =>
      value.toRadixString(2).padLeft(width, '0');

  static int _literalCount(String pattern) =>
      pattern.split('').where((bit) => bit != '-').length;

  static bool _matches(String pattern, String minterm) {
    for (int i = 0; i < pattern.length; i++) {
      if (pattern[i] != '-' && pattern[i] != minterm[i]) return false;
    }
    return true;
  }

  /// Combine two patterns differing in exactly one fixed bit, else null.
  static String? _combine(String a, String b) {
    int diff = 0;
    final result = StringBuffer();
    for (int i = 0; i < a.length; i++) {
      if (a[i] == b[i]) {
        result.write(a[i]);
        continue;
      }
      if (a[i] == '-' || b[i] == '-') return null;
      diff++;
      result.write('-');
    }
    return diff == 1 ? result.toString() : null;
  }

  static List<({String pattern, List<int> covers})> _primeImplicants(
    int n,
    List<int> targets,
  ) {
    var current = [for (final m in targets) _toBinary(m, n)];
    final primes = <String>[];

    while (current.isNotEmpty) {
      final used = List.filled(current.length, false);
      final next = <String>[];
      final seen = <String>{};

      for (int i = 0; i < current.length; i++) {
        for (int j = i + 1; j < current.length; j++) {
          final combined = _combine(current[i], current[j]);
          if (combined == null) continue;
          used[i] = true;
          used[j] = true;
          if (seen.add(combined)) next.add(combined);
        }
      }

      for (int i = 0; i < current.length; i++) {
        if (!used[i] && !primes.contains(current[i])) primes.add(current[i]);
      }
      current = next;
    }

    final targetPatterns = [for (final m in targets) _toBinary(m, n)];
    return [
      for (final pattern in primes)
        (
          pattern: pattern,
          covers: [
            for (int i = 0; i < targets.length; i++)
              if (_matches(pattern, targetPatterns[i])) targets[i],
          ],
        ),
    ];
  }

  /// All minimal covers (fewest terms, then fewest literals), deduplicated.
  static List<List<String>> _solveExactPatterns(int n, List<int> targets) {
    final implicants = _primeImplicants(n, targets);

    // Essential prime implicants: sole cover of some target.
    final essential = <int>{};
    for (final target in targets) {
      final owners = <int>[];
      for (int i = 0; i < implicants.length; i++) {
        if (implicants[i].covers.contains(target)) owners.add(i);
      }
      if (owners.length == 1) essential.add(owners.first);
    }

    final essentialPatterns = [for (final i in essential) implicants[i].pattern];
    final covered = <int>{
      for (final i in essential) ...implicants[i].covers,
    };
    final uncovered = [for (final t in targets) if (!covered.contains(t)) t];

    if (uncovered.isEmpty) return [essentialPatterns];

    final candidates = [
      for (int i = 0; i < implicants.length; i++)
        if (!essential.contains(i) &&
            implicants[i].covers.any(uncovered.contains))
          implicants[i],
    ];

    var bestTerms = 1 << 30;
    var bestLiterals = 1 << 30;
    final bestSets = <List<String>>[];

    void recurse(int at, List<int> picked, Set<int> pickedCover) {
      final totalTerms = essentialPatterns.length + picked.length;
      if (totalTerms > bestTerms) return;

      if (uncovered.every(pickedCover.contains)) {
        final patterns = [
          ...essentialPatterns,
          for (final idx in picked) candidates[idx].pattern,
        ];
        final literals = patterns.fold(0, (acc, p) => acc + _literalCount(p));

        if (totalTerms < bestTerms ||
            (totalTerms == bestTerms && literals < bestLiterals)) {
          bestTerms = totalTerms;
          bestLiterals = literals;
          bestSets
            ..clear()
            ..add(patterns);
        } else if (totalTerms == bestTerms && literals == bestLiterals) {
          bestSets.add(patterns);
        }
        return;
      }

      if (at >= candidates.length) return;

      recurse(at + 1, picked, pickedCover);
      recurse(
        at + 1,
        [...picked, at],
        {...pickedCover, ...candidates[at].covers},
      );
    }

    recurse(0, [], {});

    final seen = <String>{};
    final unique = <List<String>>[];
    for (final set in bestSets) {
      final canonical = ([...set]..sort()).join('|');
      if (seen.add(canonical)) unique.add(set);
    }
    return unique;
  }

  /// Among equally minimal covers, prefer the one that looks best on the
  /// map: fewer groups wrapping around the edges, then larger group areas.
  static List<String> _pickBestCandidate(
    List<List<String>> candidates,
    int n,
    List<int> targets,
    List<KarnaughCellRef> positionOf,
    int rowCount,
    int colCount,
  ) {
    ({int wrapPenalty, int areaScore}) score(List<String> patterns) {
      int wrapPenalty = 0;
      int areaScore = 0;
      for (final pattern in patterns) {
        final cells = [
          for (final m in targets)
            if (_matches(pattern, _toBinary(m, n))) positionOf[m],
        ];
        final rows = {for (final c in cells) c.row};
        final cols = {for (final c in cells) c.col};
        if (rowCount > 2 &&
            rows.length < rowCount &&
            rows.contains(0) &&
            rows.contains(rowCount - 1)) {
          wrapPenalty++;
        }
        if (colCount > 2 &&
            cols.length < colCount &&
            cols.contains(0) &&
            cols.contains(colCount - 1)) {
          wrapPenalty++;
        }
        areaScore += cells.length * cells.length;
      }
      return (wrapPenalty: wrapPenalty, areaScore: areaScore);
    }

    final normalized = [
      for (final candidate in candidates)
        [...candidate]..sort((a, b) {
          final diff = _literalCount(a) - _literalCount(b);
          return diff != 0 ? diff : a.compareTo(b);
        }),
    ];

    normalized.sort((a, b) {
      final sa = score(a);
      final sb = score(b);
      if (sa.wrapPenalty != sb.wrapPenalty) {
        return sa.wrapPenalty - sb.wrapPenalty;
      }
      if (sa.areaScore != sb.areaScore) return sb.areaScore - sa.areaScore;
      return a.join('|').compareTo(b.join('|'));
    });

    return normalized.first;
  }

  /// Render a pattern as an app-notation term, e.g. `(¬A ∧ C)` for SOP or
  /// `(A ∨ ¬C)` for POS, so results can be re-entered in the calculator.
  static String _patternToTerm(
    String pattern,
    List<String> variables,
    KarnaughForm form,
  ) {
    final literals = <String>[];
    for (int i = 0; i < pattern.length; i++) {
      final bit = pattern[i];
      if (bit == '-') continue;
      final negated = form == KarnaughForm.sop ? bit == '0' : bit == '1';
      literals.add(negated ? '¬${variables[i]}' : variables[i]);
    }
    if (literals.length == 1) return literals.first;
    final separator = form == KarnaughForm.sop ? ' ∧ ' : ' ∨ ';
    return '(${literals.join(separator)})';
  }
}

/// Gray code sequences used for map headers (1 or 2 bits).
List<String> _grayCodes(int bits) {
  switch (bits) {
    case 1:
      return const ['0', '1'];
    case 2:
      return const ['00', '01', '11', '10'];
    default:
      throw ArgumentError('Unsupported gray code width: $bits');
  }
}
